language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"
# command to install dependencies
install: pip install pytest -r requirements.txt
# command to run tests, e.g. python setup.py test
script: py.test tests
